### ISSUE TITLE
Issues with `git commit -v`

### ISSUE THREAD

**Issue by alejandronanez** [bk201-/jira-prepare-commit-msg#274]
Hello @bk201-

We just noticed that using this package with the `"prepare-commit-msg"` hook, will wipe out the comments you get whenever you do `git commit -v`.

In this image, you'll see what I'd expect to see on the left vs what's actually happening on the right.

![](https://cdn.zappy.app/77a101998c373fb7626c445e78e0e66f.png)

### Version

```
"jira-prepare-commit-msg": "1.4.2",
```

### Steps to reproduce

1. Make one change
2. Type `git commit -v`

### Expected result
I should see the diff from `git commit -v`, plus, the Jira ticket message that we have in this package config

### Actual result
We get the Jira ticket message that we have in this package config.

---

Are we missing something in our configuration? or maybe, we're using the wrong commit hook?

Thank you

**Comment by bk201-** [comment]
Hi @alejandronanez! I will check it tomorrow. It might be one thing that I've written at my README file as a TODO feature  - don't remove comments

**Comment by bk201-** [comment]
Hi @alejandronanez!

I've fixed it. Please check a new version 1.5.0

**Comment by alejandronanez** [comment]
Hey @bk201- thanks for the quick changes!

I'm still having some issues with the hook tho 😅, what could I be missing here? 🤔 

## My config

```json
"husky": {
    "hooks": {
      "pre-commit": "tsc --noEmit && lint-staged",
      "prepare-commit-msg": "jira-prepare-commit-msg"
    }
  },
  "jira-prepare-commit-msg": {
    "messagePattern": "$M\n\nJira: $J",
    "jiraTicketPattern": "([A-Z]+-[\\d|xxx|XXX]+)",
    "commentChar": "#",
    "isConventionalCommit": false
  },
```

## Error Message

```
❯ git commit --verbose
husky > pre-commit (node v12.16.1)
ℹ No staged files match any configured task.
husky > prepare-commit-msg (node v12.16.1)
env: node\r: No such file or directory
husky > prepare-commit-msg hook failed (cannot be bypassed with --no-verify due to Git specs)
```

## Screenshots
![](https://cdn.zappy.app/6669b39f44b4d52d5f9e9b4e85b05e49.png)

**Comment by bk201-** [comment]
@alejandronanez! Sorry, I can't reproduce this error. Could you please run package this flag `--verbose`

```
{
"prepare-commit-msg": "jira-prepare-commit-msg --verbose"
}
```

![image](https://user-images.githubusercontent.com/6812525/106916004-c0b61800-6717-11eb-85e5-37975589e72e.png)
![image](https://user-images.githubusercontent.com/6812525/106916403-2d311700-6718-11eb-9ec4-87031d95363e.png)

**Comment by alejandronanez** [comment]
Hey @bk201-, I still got the same message on my end.

After some quick 👀 , it seems that this issue could be only reproducible in MacOS (I see you're using Windows from your screenshots).

See this from Stackoverflow: https://stackoverflow.com/a/58558771/1405803

**Comment by MrRefactoring** [comment]
Hi @alejandronanez!

I am trying to reproduce the error with the message on version 1.5.0. I get the error itself with the message, but not with NodeJS. Could you provide a screenshot of the terminal where you run the commands `node -v` and `where node`

My result:

<img width="682" alt="terminal" src="https://user-images.githubusercontent.com/10329528/106936279-7344a580-672d-11eb-86b5-3ee14c515289.png">

**Comment by MrRefactoring** [comment]
@alejandronanez am I correct in assuming that when you enter the `git commit -v` command, you are using VIM to enter the message? If so, how do you exit VIM after entering the message?

**Comment by alejandronanez** [comment]
Hey @MrRefactoring, sure:

```
node -v
v12.16.1
which node
-> /Users/alejandro/.nvm/versions/node/v12.16.1/bin/node
```
> am I correct in assuming that when you enter the git commit -v command, you are using VIM to enter the message? 
That's not correct, I'm would be using VSCode to write that message. The problem is that I don't even make it to VSCode as the hook errors out before opening the editor.

**Comment by MrRefactoring** [comment]
@alejandronanez at the moment I see this behavior:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/10329528/106939915-f1a34680-6731-11eb-9dc1-dd9b70c211b3.png">

![telegram-cloud-photo-size-2-5251275733806986915-y](https://user-images.githubusercontent.com/10329528/106940044-17c8e680-6732-11eb-959d-29aabe1153a2.jpg)


![telegram-cloud-photo-size-2-5251275733806986916-y](https://user-images.githubusercontent.com/10329528/106940057-1bf50400-6732-11eb-8508-6624d1fb521f.jpg)

**Comment by MrRefactoring** [comment]
> Hey @MrRefactoring, sure:
> 
> ```
> node -v
> v12.16.1
> 
> which node
> /Users/alejandro/.nvm/versions/node/v12.16.1/bin/node
> ```
> 
> > am I correct in assuming that when you enter the git commit -v command, you are using VIM to enter the message?
> 
> That's not correct, I'm would be using VSCode to write that message. The problem is that I don't even make it to VSCode as the hook errors out before opening the editor.

Okay, what terminal are you using in VSCode? And can you run the commands `node -v` and `where node` in it?

**Comment by bk201-** [comment]
@alejandronanez Could you please share your npm version?

**Comment by alejandronanez** [comment]
@MrRefactoring hey - I'm using ZSH. I get the same values I pasted above.

@bk201- sure thing, I'll try that out later today or tomorrow morning for sure

Thanks for all your help 👍

**Comment by alejandronanez** [comment]
@bk201- `dos2unix` did  the trick! 🙌  Now it's working as expected.

**Comment by bk201-** [comment]
@alejandronanez OK, I published the 1.5.1 version (without dev postfix). Thanks a lot for your fast checking
